### ISSUE TITLE
Displaying row as column

### ISSUE THREAD

**Issue by andreastoellefsen** [formatc1702/WireViz#280] opened 2022-04-19 12:11 UTC
I'm experiencing som strange behavior when using the feature/technical-drw branch.
WireViz seems to displayed the row as a column. 
![demo02](https://user-images.githubusercontent.com/15253350/163999154-fadb71ce-3427-46af-b692-2ac3711f48ed.png)
 
When switching to the master branch everything is fine:
![demo02](https://user-images.githubusercontent.com/15253350/163999755-12c1faca-2236-4b0d-84e2-bbdcacba1c12.png)

The only thing I'm changing is the branch

Got any ideas?

I really appreciate the effort you have put into this tool!

Andreas

**Comment by andreastoellefsen** [comment] 2022-04-19 12:28
I should have noted that I'm using the examples/demo02.yml as a test

**Comment by kvid** [comment] 2022-04-19 14:05
This seems to be a duplicate of #258 that was fixed by PR #261 and then merged into master from [v0.3.2](https://github.com/formatc1702/WireViz/releases/tag/v0.3.2), but not currently included in `dev`, `latest`, or any of the PR branches. If you need this fix together with `feature/technical-drw`, then I suggest you create your own local branch from this PR branch and then either merge master into it, or cherry-pick only the fix 9af0cb8ab0314bc6754b153769f7562b5b38ec10.

**Comment by andreastoellefsen** [comment] 2022-04-19 19:31
Thanks, that did the trick!

Andreas

**Closed** 2022-08-05 19:37 UTC
